### ISSUE TITLE
WindowHandle for sending custom events to the window

### ISSUE THREAD

**Issue by DGriffin91** [BillyDM/imgui-baseview#9]
Is it possible to get this sort of functionality with imgui-baseview? 

https://github.com/BillyDM/iced_baseview/commit/6f15c791794a0875649f99cf8d42725617c86343

**Comment by BillyDM** [comment]
I believe that the build closure is called every frame, so you are able to pass your own message channel into the build closure and poll for messages yourself.

**Comment by BillyDM** [comment]
BTW `baseview` recently got a new update that should fix issues with closing/opening plugin windows. Baseview now returns a `WindowHandle` on the `open_parented()` method, which you can then call `window_handle.close()` on it when you receive an `effEditClose` VST2 event to properly close the window.
